### ISSUE TITLE
Size + card

### ISSUE THREAD

**Issue by rafaelcavalcanti** [haubek/bootstrap4c-custom-switch#1]
There is some way to resize the switch? get smaller...

And when i use with card on footer, the switch shows wrong. There is some trick?

Thanks

**Comment by haubek** [comment]
Hi Rafael. Sorry for the late reply. The custom-switch UI component doesn't support different sizes... however you can change the size values in `_component-variables.scss` and re-build the css. A smaller switch could be:
```
$switch-width:                    54;
$switch-width-status:             72;
$switch-height:                   24;
$switch-font-size:                12;
```
Alternatively you can override the class styles.
I haven't tested using the custom-switch in cards but this should work fine.

**Comment by nullbio** [comment]
Thanks so much for sharing this @haubek - this is exactly what I needed.
