### ISSUE TITLE
Checking the state of the checkbox

### ISSUE THREAD

**Issue by nabielm** [haubek/bootstrap4c-custom-switch#20]
How to check the state of the checkbox??

**Comment by irfanharunk** [comment]
Can you please share the solution as to how did you get the state of the checkbox?
unfortunately, this issue has been closed without any update/solution :(

**Comment by haubek** [comment]
Hi. The `<input>` element is used (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox). Or use JS to check attribute.

**Comment by nabielm** [comment]
@irfanharunk I created this issue to find out whether @haubek provided a method to check the state of the checkbox. You can use a simple JavaScript/jQuery code to check whether a particular checkbox is checked.

reference:

 **JavaScript**: https://www.javascripttutorial.net/javascript-dom/javascript-checkbox/

 **jQuery**: https://www.tutorialrepublic.com/faq/how-to-check-a-checkbox-is-checked-or-not-using-jquery.php

N.B: Thank you @haubek. I appreciate your work
